# Generated by Django 3.2.9 on 2021-12-03 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.TextField()),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('album', models.TextField()),
                ('album_image', models.TextField()),
                ('popularity', models.IntegerField()),
                ('danceability', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('key', models.IntegerField()),
                ('loudness', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.IntegerField()),
                ('acousticness', models.IntegerField()),
                ('instrumentalness', models.IntegerField()),
                ('liveness', models.IntegerField()),
                ('valence', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('duration_ms_y', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
